### ISSUE TITLE
Error: While performing step 6 Start REST Client Data Generator

### ISSUE THREAD

**Issue by Shamsi12** [jtmelton/appsensor#104]
When i execute this command mvn spring-boot:run after reached into the recommended directory, The execution starts but never ends (means commands on cmd are running continuously). I have   
tried many times but same error has been occurred. Kindly give possible solutions.

![appsensor error](https://user-images.githubusercontent.com/57343383/69898368-94b43f80-137a-11ea-99aa-da743a032e07.PNG)

**Comment by jtmelton** [comment]
The command is not meant to stop - it just continually generates data - it's a test data generator.

**Comment by Shamsi12** [comment]
Okay sir, so how can i execute the next step?

**Comment by jtmelton** [comment]
What next step do you mean? The data is being generated, so you should be able to see the data in your environment.
