### ISSUE TITLE
Setup CI for unit test execution

### ISSUE THREAD

**Issue by jtmelton** [jtmelton/appsensor#15]
Likely doing this with http://www.cloudbees.com/

**Comment by jtmelton** [comment]
removing everything except UI for 2.2

**Comment by brunoqc** [comment]
Did you consider using travis-ci?

You just need the webhook and a `.travis.yml` file containing :
```yaml
language: java
```

**Comment by jtmelton** [comment]
Setup travis-ci, and will be adding it to the project. However, build is currently wonky. Waiting on the influxdb-java project to push a new version that you don't have to install manually to make it work. See https://github.com/influxdb/influxdb-java/issues/37

**Comment by jtmelton** [comment]
This is now done. I temporarily disabled the influxdb integration project, and will re-enable it when their issue is resolved. 

To check on this, see : https://travis-ci.org/jtmelton/appsensor/

I also put a build badge on the main readme: https://github.com/jtmelton/appsensor/blob/master/README.md

Thanks @brunoqc for the travis-ci suggestion.
