### ISSUE TITLE
Implement output to monitoring solution

### ISSUE THREAD

**Issue by jtmelton** [jtmelton/appsensor#19]
Could be jmx, snmp, etc. 

consider https://www.suse.com/communities/conversations/application-monitoring-made-easy-java-applications-using-nagios/

**Comment by cwatson2** [comment]
Just came across this ENISA report that lists many different information sharing formats. I mention some of those in the AppSensor Guide, but will update that to reference whatever we do in the code.

https://www.enisa.europa.eu/activities/cert/support/actionable-information/standards-and-tools-for-exchange-and-processing-of-actionable-information

**Comment by jtmelton** [comment]
Added a couple of releases to this branch: https://github.com/jtmelton/appsensor/tree/dev-v2.1 . Added to build here: https://github.com/jtmelton/appsensor/commit/d8b349b0b7ba32911d0b4cc9061edf362269b070

Will close this issue when 2.1 is released.

**Comment by jtmelton** [comment]
Closed with https://github.com/jtmelton/appsensor/releases/tag/v2.1.0
