### ISSUE TITLE
Issue due to logback.xml in appsensor-core jar

### ISSUE THREAD

**Issue by prakashkiit** [jtmelton/appsensor#63]
appsensor-core has logback.xml with log level DEBUG directed to STDOUT in src/main/resources. The appsensor-core jar also gets bundled with logback.xml. It is conflicting with our logback.xml in classpath. We tried to exclude logback in pom.xml using following but has no impact.
`<exclusion>`
	`<groupId>ch.qos.logback</groupId>`
	`<artifactId>logback-classic</artifactId>`
`</exclusion>`
`<exclusion>`
	`<groupId>ch.qos.logback</groupId>`
	`<artifactId>logback-core</artifactId>`
`</exclusion>`

**Comment by jtmelton** [comment]
@prakashkiit Thanks for creating the issue. 

Is your goal that the logback.xml be removed completely, or are you hoping for some other change?

**Comment by prakashkiit** [comment]
As a workaround, we had to packaged our jar with appsensor-core classes only to exclude the logback.xml. So in my suggestion you can move logback.xml from src/main/resources to src/test/resources so it will not get packaged with jar.

**Comment by jtmelton** [comment]
Thanks @prakashkiit . I'll try to get this resolved in the next day or so.

**Comment by jtmelton** [comment]
@prakashkiit I just pushed a change that hopefully will resolve the issue for you. Please have a look and let me know if that is what you need. If so, I'll cut another release to make sure it's in central for you. https://github.com/jtmelton/appsensor/commit/a4d395c0adbe52f89273dce95ec0b6bfdd892767#diff-f528abbbd70aa68ea22dd3d29d7db851

**Comment by prakashkiit** [comment]
Thank you @jtmelton . This looks good. Please let me know once the updated jar is in central. I will pull it.

**Comment by jtmelton** [comment]
Ok @prakashkiit , it looks like central finally picked up the updates - I moved to 2.3.1. Can you verify and then close if that solves your issue?

**Comment by prakashkiit** [comment]
Thank you very much @jtmelton for such quick turnaround. I have downloaded 2.3.1 version and working fine with no issues. I am closing this issue. Thanks again.

**Comment by jtmelton** [comment]
Perfect - thanks for filing and then working through it with me @prakashkiit
