### ISSUE TITLE
rules engine breaks appsensor-ui

### ISSUE THREAD

**Issue by jtmelton** [jtmelton/appsensor#68]
Trying to get AppSensor Demo Setup running, following instructions at
https://github.com/jtmelton/appsensor/blob/master/sample-apps/DemoSetup.md

Everything goes fine until trying to start AppSensorUI which fails with:

Unable to build Hibernate SessionFactory: @OneToOne or @ManyToOne on
org.owasp.appsensor.core.Attack.rule references an unknown entity:
org.owasp.appsensor.core.rule.Rule

This is part of a huge stack trace, but I believe that's the useful
part. I could post the entire thing but it's rather long.

I don't know Hibernate. Is there something wrong with my setup, or is
this an issue with the code?

Regards,
Geir H. Hansen

**Comment by jtmelton** [comment]
Looks like this is broken due to new rules engine code. @dscrobonia can you take a look and see if it's obvious?

**Comment by jtmelton** [comment]
also @dscrobonia if there's a way to add a unit test to cover it, that'd be awesome.

**Comment by dscrobonia** [comment]
Will do!

**Comment by jtmelton** [comment]
Reopened to allow for review.

**Comment by jtmelton** [comment]
This issue was opened by a customer (Geir H. Hansen) over email, and he just confirmed it is now resolved.
