### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by clarabridges** [jtmelton/appsensor#80]
Need to add dependency to javax.annotation-api in the pom otherwise some of the tests don't run when doing mvn install and the install fails.

```
Caused by: java.lang.ClassNotFoundException: javax.annotation.security.RolesAllowed
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 137 more

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
.......
[INFO] appsensor-local .................................... SUCCESS [ 14.070 s]
[INFO] appsensor-storage-file-based ....................... SUCCESS [  4.653 s]
[INFO] appsensor-ws-rest-server ........................... FAILURE [ 11.110 s]
.......
```

**Comment by jtmelton** [comment]
@clarabridges thanks for the issue. I just pulled a fresh copy, and was able to install locally. I ran the 4 following steps. Do these work for you? 

1. `git clone https://github.com/jtmelton/appsensor.git`
2. `cd appsensor`
3. `mvn -N install`
4. `mvn install`

**Comment by clarabridges** [comment]
Those are the steps I followed. Have you tried blowing away your .m2 dir? It's possible you may already have had the jar installed there. When I removed mine I was able to replicate.

**Comment by jtmelton** [comment]
@clarabridges yes, I just tried that locally (didn't the first time) - removed the .m2 dir, and ran a full rebuild pulling everything back down. Also, I tried running `mvn dependency:tree | grep annotation-api` and got this as a response

`
mvn dependency:tree | grep annotation-api
[INFO] |  |  +- javax.annotation:javax.annotation-api:jar:1.2:compile
[INFO] |  |  +- javax.annotation:javax.annotation-api:jar:1.2:compile
[INFO] |  |  +- javax.annotation:javax.annotation-api:jar:1.2:compile
[INFO] |  |  +- javax.annotation:javax.annotation-api:jar:1.2:compile
[INFO] |  |  +- javax.annotation:javax.annotation-api:jar:1.2:compile
`

**Comment by jtmelton** [comment]
closing as old ....
