### ISSUE TITLE
Move project to OWASP organization?

### ISSUE THREAD

**Issue by Neil-Smithline** [jtmelton/appsensor#82]
I'm wondering if this project should be moved to the [GitHub OWASP organization](https://github.com/OWASP/). Besides making it easier for people to find, that provides some security in case you're hit by a falling piano or something. I guess I don't feel strongly about it, but thought I'd mention it.

**Comment by jtmelton** [comment]
@Neil-Smithline I'm not necessarily opposed to it, but would like to see a plan from the community on how that should look. I'm fine to do it going forward if people are interested. From my perspective, I'd want to see all flagship projects handled the same way if possible. There have been a couple false starts before, so I'd like to see the plan before making changes.
