### ISSUE TITLE
Using AppSensor with my C# ASP.NET Web application 

### ISSUE THREAD

**Issue by ARUimran** [jtmelton/appsensor#83]
I was following the AppSensor developer guide which listed a variety of dependencies required. I downloaded these and added these to my project but I wasn't sure how to actually use AppSensor with the project. I have a lot of confusion over which API to access and how to do so, as I'm very unfamiliar with maven and jar files as well as accessing the AppSensor API/REST API's from my Application. 

Building the AppSensor with maven seemed to work and running the demo apps seemed fine too, I'm just not sure where to go from here in terms of using it in my project.

**Comment by ProZachJ** [comment]
Is suggest starting here to get a feel for how to use AppSensor

https://youtu.be/1imlD1O4HrY

https://www.owasp.org/index.php/File:Appsensor_intro_for_developers.pdf

Those resources should give you a clearer picture of how to integrate
AppSensor into your application.

**Comment by jtmelton** [comment]
Thanks for the pointers @ProZachJ . 

@ARUimran A few extra thoughts. 

1. You'll essentially need to use a C# REST client to interact with the server. If you look at the RestRequestHandler section here: http://appsensor.org/docs/v2.3.0/api/ui/index.html , you can see the events/attacks/responses apis that you'll want to interact with. 

2. There are a number of ways to put the API calls in place. The video @ProZachJ linked walks through several ideas. For testing, I'd suggest starting with the simplest code you can. That could be just writing code to interact with the REST client directly. Once you get that working, you'll likely want to make a more user-friendly mechanism of implementation, using domain objects, or exceptions, or middleware to do this type of work. 

3. There are probably a few issues you could use to get some ideas, but here's a recent one that's similar, but for python: https://github.com/jtmelton/appsensor/issues/81

Hope this helps!

**Comment by ARUimran** [comment]
Thanks for the response.

I believe the main problem I'm having right now before using the REST clients etc is using the AppSensor jar files and libraries with my C# code, and I'm struggling to find out how to do this.

**Comment by jtmelton** [comment]
@ARUimran Ahh, I understand better now. There is no pre-built C# client library to use. You have 2 basic options: 
1. Use the http api directly. That means you'll be using a standard C# rest client and having to write code, but it should be pretty straightforward, and there are really only a few APIs you'll want to work with and they are listed here: http://appsensor.org/docs/v2.3.0/api/ui/index.html under the RestRequestHandler section
2. Generate a client library. If you take a look at https://github.com/jtmelton/appsensor/tree/master/client-libs there is a README there that covers generating a client library. You can feel free to do this, and the instructions should be on that page.

**Comment by ARUimran** [comment]
Apologies if I seem like I'm lacking knowledge on this, but the README for generating a client library only shows how to generate libraries for java and python. I'm also not sure about getting the REST API server running so that it can be accessed it through my browser and my C# web application.

**Comment by jtmelton** [comment]
So, if you run the sample app, there is a REST server is running. If you don't want to run the sample app, then your best bet is to run this app - the readme on this page should get you going - https://github.com/jtmelton/appsensor/tree/master/sample-apps/appsensor-ws-rest-server-boot. 
As for the client libraries, you're correct that only java and python were done, but they were simply done as examples. You should be able to generate one for c# by doing something very similar to the java/python instructions listed on the readme, but changing them to c#. We're using this tool: https://github.com/swagger-api/swagger-codegen. Hope this helps.

**Comment by ARUimran** [comment]
I think I successfully created the c# client library but I'm not sure how to access the library that was created from my project. I can get the REST server running but I don't know how to get this to interact with the http api directly.

**Comment by jtmelton** [comment]
@ARUimran the key part of Damien's problem was that he was sending the wrong header name/value. 

Note: "All I needed to do was add X-Appsensor-Client-Application-Name2: myclientapp in the Request Header of the Client that was going to use the API."

In order to make this work, you'll likely have to debug your c# application to see the actual request being sent. Presumably there's an http client library being used. If you walk through it with a debugger, you should be able to see the http request being sent, as well as the http response (and error/stacktrace in c#) that comes back. Based on that, I can try and help debug a bit.

**Comment by ARUimran** [comment]
I believe I've figured out how to add the header in the request header of the client, but I'm having trouble constructing the POST/GET requests upon activation of a detection point based on the ones under the RestRequestHandler section, and I'm not sure if it should be interacting with the standard http api or the REST server or if that's what I'm meant to be doing.

**Comment by jtmelton** [comment]
Yeah, the way it would work is essentially in code like this: 
```
void myMethod() {
    if (! user.isAuthorized(recordId)) {
        // this is an authorization problem
        appsensor.sendEvent("ACE1");    // NOTE: THIS IS WHERE THE HTTP POST IS MADE
        throw new AuthorizationException("User is not authorized");
    }
}
```
The POST should go to the REST server (I think runs on 8085 by default). You'll make that POST request to `/api/v1.0/events` and you'll send along the information for the event as the POST body (in json, see the api documentation at http://appsensor.org/docs/v2.3.0/api/ui/index.html under RestRequestHandler.

**Comment by ARUimran** [comment]
I have been using the following code that I have written:

    public async Task<HttpResponseMessage> events()
    {
        try
        {
            client.BaseAddress = new Uri("http://localhost:8085/");
        }
        catch (InvalidOperationException)
        { }
        client.DefaultRequestHeaders.Accept.Clear();
        client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        client.DefaultRequestHeaders.Add("X-Appsensor-Client-Application-Name2", "myclientapp");
        HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Post, "api/v1.0/events");
        request.Content = new StringContent("AE3",
                                            Encoding.UTF8,
                                            "application/json");


        HttpResponseMessage response = await client.PostAsJsonAsync("api/v1.0/events", request);

        System.Diagnostics.Debug.WriteLine(response.ToString());
        return response;
    }
But this is the response I get:

StatusCode: 400, ReasonPhrase: 'Bad Request', Version: 1.1, Content: 
System.Net.Http.StreamContent, Headers:

{
  Connection: close
  Date: Sun, 04 Mar 2018 23:46:17 GMT
  Server: Apache-Coyote/1.1
  Content-Length: 402
  Content-Type: text/plain; charset=UTF-8
}
I'm not sure what I've done wrong in the request.

**Comment by ARUimran** [comment]
I realised I think I need to POST the json body like this as similar to the #81 issue.
`{"user":{"username":"bob"},"detectionPoint":{"category":"Access Control","label":"ACE3","responses":[]},"timestamp":"2018-02-18T18:54:58.506Z","detectionSystem" {"detectionSystemId":"localhostme", "ipAddress":"10.20.30.40"}}`

Is this the solution to my current problem?

**Comment by jtmelton** [comment]
Yes, that's correct. That will likely solve the issue.

**Comment by ARUimran** [comment]
I'm still getting the same "StatusCode: 400, ReasonPhrase: 'Bad Request'" error, is this because I need to get attacks working for events to work?

**Comment by jtmelton** [comment]
@ARUimran no that shouldn't be it. If you got the demo setup to work, you should be able to start the client data generator, and then look at the output on the screen - it prints valid json for you to copy/paste as an example.

**Comment by ARUimran** [comment]
OK, I believe I have events working now, but how do I know when to POST an attack instead of just an event?

**Comment by jtmelton** [comment]
It depends on your situation. Many (maybe even most) applications will only ever submit events to appsensor. Attacks are generated based on the configuration setup in appsensor-server-config.xml. If you have a policy that says 5 events in 2 minutes, then if you send 5 events in < 2 minutes, appsensor itself will recognize that as an attack, and generate an attack for you. However, you do have the option to send in an attack yourself. If you want to send attacks yourself, the idea is that you should basically be doing the analysis yourself. You might consider doing this in some middleware or maybe a proxy or some network security appliance. Hope that helps.

**Comment by ARUimran** [comment]
I think that's covered everything I needed, and I'd just like to say thanks for all the extensive help and guidance that you've given, it is highly appreciated.

**Comment by jtmelton** [comment]
Absolutely - thanks for the feedback - it'll help us make the project better!
