### ISSUE TITLE
MySQL setup script not working?

### ISSUE THREAD

**Issue by tghosth** [jtmelton/appsensor#84]
I am trying to follow the instructions [here](https://github.com/jtmelton/appsensor/blob/master/sample-apps/DemoSetup.md) to setup a demo of AppSensor and I got to the stage where it tells me to run [this script](https://github.com/jtmelton/appsensor/blob/master/appsensor-ui/src/main/resources/db/scripts/V1_Initial_Schema_Creation.sql)

MySQL does not appear to like the table name `groups` but when I replaced the table name `groups` with `` `groups` `` throughout the script then it works.

However, I presume that if there are queries or something later on that also try and use groups without the backticks, that will also cause problems.

Any ideas?

**Comment by tghosth** [comment]
So it failed out later on with a horrible cascade of exceptions at the "Start AppSensorUI" stage although it is possible/likely that is completely unrelated. I will have a read through the guide and see if that helps with anything.

**Comment by jtmelton** [comment]
@tghosth I suspect this is b/c groups was recently moved to a reserved keyword in mysql. I updated the script (see https://github.com/jtmelton/appsensor/commit/6061056bc56a0f8c8a0618ab3de08ddb14a1ae99) - can you give that a shot?

**Comment by tghosth** [comment]
Thanks for the quick response :) will try take a look in the next few days. Is that reserved words issue likely to manifest itself anywhere else?

**Comment by jtmelton** [comment]
It's possible. I've tried to cover the other places I saw possible issues, but please let me know if you find more.

**Comment by tghosth** [comment]
Thanks for merging the follow-up PR (#85). I have another issue but I think I will open that separately because I don't think it is related.
