### ISSUE TITLE
appsensor-ui view by user and detection points fails

### ISSUE THREAD

**Issue by Viktor-ret** [jtmelton/appsensor#91]
Dear appsensor team.
I guess there is an additional timezone bug in appsensor-ui application.
It looks like the same issue which was already discussed and partially fixed in https://github.com/jtmelton/appsensor/issues/31
Commit:
https://github.com/jtmelton/appsensor/commit/c1b4270cdb93db2bc9506e1d14b51809e7443741

I'm not able to view information by user or detection Point.
There is an example with log sections.

Views which doesn't work in the browser:
http://localhost:8084/users/bob
http://localhost:8084/detection-points/IE1 (any detection label)

Log section of appsensor-ws-rest-server-with-websocket-boot:

```
10:21:10.129 [http-nio-8085-exec-9] ERROR o.a.c.c.C.[.[.[.[jerseyServlet] - Servlet.service() for servlet [jerseyServlet] in context with path [] threw exception [java.lang.IllegalArgumentException: Invalid format: "2018-06-20T09:21:10 02:00" is malformed at " 02:00"] with root cause
java.lang.IllegalArgumentException: Invalid format: "2018-06-20T09:21:10 02:00" is malformed at " 02:00"
```

Log section of appsensor-ui:

```
2018-06-20 10:21:10.127  INFO 10663 --- [nio-8084-exec-1] o.o.a.ui.rest.RestReportingEngineFacade  : Making REST call to http://localhost:8085 ... with path of /api/v1.0/reports/events
2018-06-20 10:21:10.132 ERROR 10663 --- [nio-8084-exec-1] o.o.a.u.h.AssociatedApplicationsFilter   : Error setting associated applications.
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is javax.ws.rs.NotFoundException: HTTP 404 Not Found
```

Failed REST request of appsensor-ui, captured with tcpdump:

```
10:28:36.600893 IP localhost.33954 > localhost.8085: Flags [P.], seq 6350:6640, ack 3011, win 509, options [nop,nop,TS val 3003620344 ecr 3003620344], length 290
E..V.4@.@.Ik.........................J.....
........GET /api/v1.0/reports/events?earliest=2018-06-20T09:28:36+02:00 HTTP/1.1
X-Appsensor-Client-Application-Name2: myclientapp
User-Agent: Jersey/2.14 (HttpUrlConnection 1.8.0_162)
Host: localhost:8085
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
Connection: keep-alive


10:28:36.605335 IP localhost.8085 > localhost.33954: Flags [P.], seq 3011:3120, ack 6640, win 518, options [nop,nop,TS val 3003620345 ecr 3003620344], length 109
E...^[@.@..................................
........HTTP/1.1 404 Not Found
Server: Apache-Coyote/1.1
Content-Length: 0
Date: Wed, 20 Jun 2018 08:28:36 GMT
```

**Comment by jtmelton** [comment]
@Viktor-ret thanks for the bug report. I located a couple fixes that were necessary, and patched them (https://github.com/jtmelton/appsensor/commit/748cde50f4345bf463f8eea568e1813d17383c60) and made a release: https://github.com/jtmelton/appsensor/releases/tag/v2.3.3 . The issue was that the previously fixed issue was replicated in a couple places that didn't get fixed. Thanks for tracking this down.

Please let me know if you have further issues.

**Comment by Viktor-ret** [comment]
@jtmelton thank you for the quick answer.
I'm sorry but the changes in detection-point.js and user.js didn't solve the issue.
I have still the same execptions, shown in my first post. Let me know if you need more information.

**Comment by jtmelton** [comment]
@Viktor-ret just to clarify, you pulled the latest version (2.3.3) and got the same issues?

**Comment by Viktor-ret** [comment]
@jtmelton Just tried again today and it works. I can't explain it to myself.
I'm sorry for the inconvenience. Thank you.

**Comment by jtmelton** [comment]
@Viktor-ret No problem - glad to hear it's working
