### ISSUE TITLE
How to edit the login page

### ISSUE THREAD

**Issue by Warok21** [jtmelton/appsensor#95]
Hi, 
We want to make a demo of Appsensor, but we didn't understand how to edit the login page and to make the events appears in the dashboard.

Thanks for the help

Warok

**Comment by jtmelton** [comment]
Are you using the appsensor demo and UI described here - https://github.com/jtmelton/appsensor/blob/master/sample-apps/DemoSetup.md ? If so, which part is not working? You should be able to clone/edit that code and make any updates you need.

**Comment by Warok21** [comment]
We dont understand where we can modify the login page, for example make our own attacks
________________________________
De : John Melton <notifications@github.com>
Envoyé : vendredi, 3 mai 2019 06:38
À : jtmelton/appsensor
Cc : Warok21; Author
Objet : Re: [jtmelton/appsensor] How to edit the login page (#95)


Are you using the appsensor demo and UI described here - https://github.com/jtmelton/appsensor/blob/master/sample-apps/DemoSetup.md ? If so, which part is not working? You should be able to clone/edit that code and make any updates you need.

**Comment by jtmelton** [comment]
Ah, ok. The data for the demo environment is being generated by this app https://github.com/jtmelton/appsensor/tree/master/sample-apps/appsensor-ws-rest-client-boot-data-generator , which just sends requests to the REST api. As for how to call the REST api - the docs are here: http://appsensor.org/docs/v2.3.0/api/ui/index.html .. hope that helps!

**Comment by Warok21** [comment]
Yes, it helped
Thanks 😉
________________________________
De : John Melton <notifications@github.com>
Envoyé : mercredi, 8 mai 2019 06:32
À : jtmelton/appsensor
Cc : Warok21; Author
Objet : Re: [jtmelton/appsensor] How to edit the login page (#95)


Ah, ok. The data for the demo environment is being generated by this app https://github.com/jtmelton/appsensor/tree/master/sample-apps/appsensor-ws-rest-client-boot-data-generator , which just sends requests to the REST api. As for how to call the REST api - the docs are here: http://appsensor.org/docs/v2.3.0/api/ui/index.html .. hope that helps!
