### ISSUE TITLE
Difficulties understanding the non-local AppSensor implementations

### ISSUE THREAD

**Issue by Ooooooooooooof** [jtmelton/appsensor#97]
I have managed to get an idea of the overall concept of the AppSensor architecture while playing with the `demo-appsensor-local` sample. In that implementation the `LocalResponseAnalysisEngine` calls `responseHandler.handle(response)` so the responses will be handled by their specific methods of the `userManager` implementation. 

I read somewhere that in a non-local AppSensor implementation this is managed via polling (or some push mechanism like websockets).
How would you implement that, for example, in the mentioned `demo-appsensor-local` sample? You would have to call `getResponses` in your client periodically, am I right? But how do you handle the resulting responses so the right `userManager` actions get executed?

Another uncertainty of mine is: How would you implement the AppSensor in a non java application on the client side? Would you have to reconstruct the AppSensor client components in the applied language due to not being able to add the `appsensor-core` dependency as you would in a java environment?

Thank you in advance!

**Comment by jtmelton** [comment]
@Ooooooooooooof 
For your first question, the general idea is that you would typically do a pull-based watch of the "responses". The most popular protocols for communication are REST and Kafka. You would setup appsensor to be a standalone server, and then your individual application(s) would be client(s). The client then sends events to appsensor server, which processes these and generates the results (stored locally). The client then either polls (REST / Kafka), or gets notified (Kafka / WebSocket) of a response, and it's then up to the client to deal with the response in an application-specific way. You would typically deal with the responses in your own framework or custom code however you want. There is a sample implementation for spring security, but that's the only framework support provided out of the box. (https://github.com/jtmelton/appsensor/blob/master/sample-apps/DemoSetup.md might be helpful)
For your second question, you would have to use a non-local implementation. As above, you would choose REST or Kafka (or one of the other supported execution modes), and then it's as simple as either writing or generating a REST client, or kafka client, etc. (https://github.com/jtmelton/appsensor/blob/master/client-libs/README.md and the request handler bit of http://appsensor.org/docs/v2.3.0/api/ui/index.html might be helpful)
Thanks!

**Comment by Ooooooooooooof** [comment]
> For your first question, the general idea is that you would typically do a pull-based watch of the "responses". The most popular protocols for communication are REST and Kafka. You would setup appsensor to be a standalone server, and then your individual application(s) would be client(s). The client then sends events to appsensor server, which processes these and generates the results (stored locally). The client then either polls (REST / Kafka), or gets notified (Kafka / WebSocket) of a response, and it's then up to the client to deal with the response in an application-specific way. You would typically deal with the responses in your own framework or custom code however you want. There is a sample implementation for spring security, but that's the only framework support provided out of the box. (https://github.com/jtmelton/appsensor/blob/master/sample-apps/DemoSetup.md might be helpful)

What would such an implementation looks like using the polling mechanism (I am not familiar with websockets)? Let's assume I would want to change the `demo-appsensor-local` sample to the client-side of a AppSensor REST implementation. A pull-based watch of the responses would be the periodical calling of the `getResponses` method from the `RestEventManager` class, which sends a POST request to the standalone AppSensor server. A reasonable approach could be: Every time an event gets generated in my client-side program logic I call the `getResponses` method afterwards and handle the returned collection of responses by a custom response manager which I have to create. 
Is my whole idea of this concept somewhat right?

> For your second question, you would have to use a non-local implementation. As above, you would choose REST or Kafka (or one of the other supported execution modes), and then it's as simple as either writing or generating a REST client, or kafka client, etc. (https://github.com/jtmelton/appsensor/blob/master/client-libs/README.md and the request handler bit of http://appsensor.org/docs/v2.3.0/api/ui/index.html might be helpful)

I went through the `client-libs` folder and the belonging `README`. After exploring the Swagger Codegen Maven Plugin and learning of its functionality it got clearer to me. With this tool/plugin I can generate a language specific archive, which includes all the necessary client-side compontents so I dont have to reconstruct all `appsensor-core` components in the respective language, am I right with this conclussion?
But there is still a small question left: Why is there a Java client lib listed in the mentioned folder? If I wanted to implement the AppSensor client-side components to a Java program, I would use the `RestEventManager` class to handle the communication between the client and the standalone AppSensor server. Is there a unique selling point of the listed Java client lib?

Thanks so much for your help and the fast replies!

**Comment by jtmelton** [comment]
@Ooooooooooooof 
For the polling, yes, though there are a couple caveats: 
1. Polling only immediately after sending a request could be problematic due to timing. The addEvent request is not necessarily synchronous, so there _can_ be a lag between adding an event and the response getting created. 
2. There is support for correlating events across multiple clients (sharded infra, or even multiple apps with a shared user base), so there is often a reason to poll regularly. Typically I would poll once per 30 seconds or minute for most standard apps.

For client lib generation, yes, but if you're going with the REST capability, it is pretty straightforward even if you don't generate the client. I prefer to generate, but you don't have to. You just have to match the published REST api for the version you're using.

For the java client, you're right that there's no real reason to use that. It was just showing that you could generate a client just as easily as write one directly. The client generation code was done by a student as a summer of code project a couple years back, so he just generated java/python as examples.

Hope this helps!
